repos:
  - repo: local
    hooks:
      - id: raster-to-webp
        name: Convert PNG/JPG to WebP
        entry: scripts/image-to-webp.sh
        language: script
        files: \.(png|jpg|jpeg|JPG|JPEG)$
        pass_filenames: true
      - id: check-date-match
        name: Sync Filename Date and Metadata
        entry: python3 scripts/check-dates.py
        language: python
        files: \.md$
        pass_filenames: true
      - id: auto-add-tags
        name: Auto-add matching tags
        entry: python3 scripts/auto-add-tags.py
        language: python
        files: ^content/.*\.md$
        pass_filenames: true
      - id: reorder-frontmatter
        name: Reorder front matter
        entry: python3 scripts/reorder-frontmatter.py
        language: python
        files: ^content/.*\.md$
        pass_filenames: true
      - id: validate-frontmatter
        name: Validate required front matter
        entry: python3 scripts/validate-frontmatter.py
        language: python
        files: ^content/.*\.md$
        pass_filenames: true
      - id: update-raster-refs
        name: Update Markdown PNG/JPG refs to WebP
        entry: python3 scripts/update-raster-refs-to-webp.py
        language: python
        files: ^content/.*\.md$
        pass_filenames: true

  - repo: https://github.com/lycheeverse/lychee
    rev: nightly
    hooks:
      - id: lychee
        name: Check links with Lychee
        args:
          - --offline
          - --no-progress
          - --include-fragments
          - --root-dir=.
          - --fallback-extensions=md,html,_index.md
          - "--remap=/assets/(.*) /static/assets/$1"
          - "--remap=/images/(.*) /static/images/$1"
          - "--remap=/videos/(.*) /static/videos/$1"
          - "--remap=/audios/(.*) /static/audios/$1"
          - "content/"
        files: ^content/.*\.(md|html)$
