# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cumstadistica
description: >- # this means to ignore newlines until "baseurl:"
  Página web oficial del trío cumstadístico
url:  https://cumstadistica.github.io # the base hostname & protocol for your site, e.g. http://example.com

safe: false
excerpt_separator: <!--leer-más-->


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-optional-front-matter
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-webp

markdown: kramdown

kramdown:
  input: GFM           # GitHub-Flavored Markdown (optional, useful for tables etc.)
  hard_wrap: false     # Recommended: avoid inserting <br> on line breaks
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight" # CSS class for syntax highlighting
    line_numbers: true      # Show line numbers in code blocks
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"] # Use smart quotes for apostrophes


sass:
  load_paths:
    - _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts: {categories: post, tags: archive, default: post}
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'

feed:
  path: feed.xml
  excerpt_only: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
